# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user-service/alloweddomain/service.proto for package 'bannote.userservice.alloweddomain.v1'

require 'grpc'
require 'user-service/alloweddomain/service_pb'

module Bannote
  module Userservice
    module Alloweddomain
      module V1
        module AllowedDomainService
          # Gateway에서 gRPC metadata로 전달되는 정보:
          # - user-id: 요청하는 유저의 ID
          # - user-role: 요청하는 유저의 역할 (ADMIN, STUDENT, EMPLOYEE 등)
          #
          # The domain allowlist service definition.
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.userservice.alloweddomain.v1.AllowedDomainService'

            #  도메인 허용 목록 추가 API
            rpc :AddAllowedDomain, ::Bannote::Userservice::Alloweddomain::V1::AddAllowedDomainRequest, ::Bannote::Userservice::Alloweddomain::V1::AddAllowedDomainResponse
            #  도메인 허용 목록 삭제 API
            rpc :RemoveAllowedDomain, ::Bannote::Userservice::Alloweddomain::V1::RemoveAllowedDomainRequest, ::Bannote::Userservice::Alloweddomain::V1::RemoveAllowedDomainResponse
            #  도메인 허용 목록 전체 조회 API
            rpc :ListAllowedDomain, ::Bannote::Userservice::Alloweddomain::V1::ListAllowedDomainRequest, ::Bannote::Userservice::Alloweddomain::V1::ListAllowedDomainResponse
            # 이메일을 이용하여 허용된 도메인인지 검증 API
            rpc :CheckAllowedDomain, ::Bannote::Userservice::Alloweddomain::V1::CheckAllowedDomainRequest, ::Bannote::Userservice::Alloweddomain::V1::CheckAllowedDomainResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
