# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: group_tag/group_tag.proto

require 'google/protobuf'


descriptor_data = "\n\x19group_tag/group_tag.proto\x12$bannote.scheduleservice.group_tag.v1\"<\n\x08GroupTag\x12\x19\n\x08group_id\x18\x01 \x01(\x03R\x07groupId\x12\x15\n\x06tag_id\x18\x02 \x01(\x03R\x05tagId\"e\n\x14GroupTagListResponse\x12M\n\ngroup_tags\x18\x01 \x03(\x0b\x32..bannote.scheduleservice.group_tag.v1.GroupTagR\tgroupTagsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Scheduleservice
    module GroupTag
      module V1
        GroupTag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.group_tag.v1.GroupTag").msgclass
        GroupTagListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.group_tag.v1.GroupTagListResponse").msgclass
      end
    end
  end
end
