# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: allowedemail/allowedemail.proto

require 'google/protobuf'


descriptor_data = "\n\x1f\x61llowedemail/allowedemail.proto\x12#bannote.userservice.allowedemail.v1\"C\n\x0c\x41llowedEmail\x12\x14\n\x05\x65mail\x18\x01 \x01(\tR\x05\x65mail\x12\x1d\n\ncreated_by\x18\x02 \x01(\tR\tcreatedByB|\n.com.bannote.userservice.proto.allowed_email.v1P\x01ZHgithub.com/kyumin1227/bannote-proto/gen/go/user-service/allowed_email/v1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Userservice
    module Allowedemail
      module V1
        AllowedEmail = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.userservice.allowedemail.v1.AllowedEmail").msgclass
      end
    end
  end
end
