syntax = "proto3";

package bannote.scheduleservice.schedule_link.v1;

import "google/protobuf/timestamp.proto";

message ScheduleLink {
  int64 link_id = 1;
  int64 schedule_id = 2;
  string title = 3;
  optional int64 place_id = 4;
  optional string place_text = 5;
  string description = 6;
  string start_at = 7; // YYYY-MM-DDTHH:mm
  string end_at = 8; // YYYY-MM-DDTHH:mm
  bool is_allday = 9;
  int64 created_by = 10;
  google.protobuf.Timestamp created_at = 11;
  optional google.protobuf.Timestamp updated_at = 12;
}
