# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

require 'google/protobuf'


descriptor_data = "\n\x0c\x63ommon.proto\x12!bannote.scheduleservice.common.v1\"\x07\n\x05\x45mptyBPZNgithub.com/kyumin1227/bannote-proto/gen/go/schedule_service/common/v1;commonv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Scheduleservice
    module Common
      module V1
        Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.common.v1.Empty").msgclass
      end
    end
  end
end
