# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schedule-service/user_group/user_group_service.proto

require 'google/protobuf'

require 'schedule-service/user_group/user_group_pb'


descriptor_data = "\n4schedule-service/user_group/user_group_service.proto\x12\x1f\x62\x61nnote.scheduleservice.user.v1\x1a,schedule-service/user_group/user_group.proto\"K\n\x15\x41\x64\x64UserToGroupRequest\x12\x19\n\x08group_id\x18\x01 \x01(\x03R\x07groupId\x12\x17\n\x07user_id\x18\x02 \x01(\x03R\x06userId\"3\n\x16GetUsersInGroupRequest\x12\x19\n\x08group_id\x18\x01 \x01(\x03R\x07groupId\"1\n\x16GetGroupsOfUserRequest\x12\x17\n\x07user_id\x18\x01 \x01(\x03R\x06userId\"P\n\x1aRemoveUserFromGroupRequest\x12\x19\n\x08group_id\x18\x01 \x01(\x03R\x07groupId\x12\x17\n\x07user_id\x18\x02 \x01(\x03R\x06userId\"7\n\x1bRemoveUserFromGroupResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success2\xb7\x04\n\x10UserGroupService\x12\x81\x01\n\x0e\x41\x64\x64UserToGroup\x12\x36.bannote.scheduleservice.user.v1.AddUserToGroupRequest\x1a\x37.bannote.scheduleservice.user.v1.AddUserToGroupResponse\x12\x84\x01\n\x0fGetUsersInGroup\x12\x37.bannote.scheduleservice.user.v1.GetUsersInGroupRequest\x1a\x38.bannote.scheduleservice.user.v1.GetUsersInGroupResponse\x12\x84\x01\n\x0fGetGroupsOfUser\x12\x37.bannote.scheduleservice.user.v1.GetGroupsOfUserRequest\x1a\x38.bannote.scheduleservice.user.v1.GetGroupsOfUserResponse\x12\x90\x01\n\x13RemoveUserFromGroup\x12;.bannote.scheduleservice.user.v1.RemoveUserFromGroupRequest\x1a<.bannote.scheduleservice.user.v1.RemoveUserFromGroupResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Scheduleservice
    module User
      module V1
        AddUserToGroupRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.user.v1.AddUserToGroupRequest").msgclass
        GetUsersInGroupRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.user.v1.GetUsersInGroupRequest").msgclass
        GetGroupsOfUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.user.v1.GetGroupsOfUserRequest").msgclass
        RemoveUserFromGroupRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.user.v1.RemoveUserFromGroupRequest").msgclass
        RemoveUserFromGroupResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.user.v1.RemoveUserFromGroupResponse").msgclass
      end
    end
  end
end
