# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alloweddomain/alloweddomain.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\n!alloweddomain/alloweddomain.proto\x12$bannote.userservice.alloweddomain.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x01\n\rAllowedDomain\x12\x16\n\x06\x64omain\x18\x01 \x01(\tR\x06\x64omain\x12\x1d\n\ncreated_by\x18\x02 \x01(\tR\tcreatedBy\x12\x39\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAtB~\n/com.bannote.userservice.proto.allowed_domain.v1P\x01ZIgithub.com/kyumin1227/bannote-proto/gen/go/user-service/allowed_domain/v1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Userservice
    module Alloweddomain
      module V1
        AllowedDomain = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.userservice.alloweddomain.v1.AllowedDomain").msgclass
      end
    end
  end
end
